chore: Add Ci for swift 2

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -1,4 +1,4 @@
-name: "build-and-test"
+name: build-and-test
 
 on:
   pull_request:
@@ -7,20 +7,37 @@ on:
     branches: [main, build_test]
 
 jobs:
+  check-xcodeproj:
+    name: Check Xcode Project
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Ensure Xcode project file exists
+        run: |
+          if [ ! -f 'BoxSdkGen.xcodeproj/project.pbxproj' ]; then
+            echo '❌ Xcode project file 'BoxSdkGen.xcodeproj/project.pbxproj' not found'
+            echo 'It will be added in the next commit into this PR with title \"chore: Generate xcode project\"'
+            exit 1
+          else
+            echo '✅ Xcode project file found'
+          fi
+
   iOS:
     name: ${{ matrix.name }}
     runs-on: ${{ matrix.runsOn }}
+    needs: check-xcodeproj
 
     strategy:
       matrix:
         include:
-          - destination: "OS=18.0,name=iPhone 16 Pro"
-            name: "xcodebuild (iOS 18.0)"
-            xcode: "Xcode_16.0"
+          - destination: 'OS=18.0,name=iPhone 16 Pro'
+            name: 'xcodebuild (iOS 18.0)'
+            xcode: 'Xcode_16.0'
             runsOn: macOS-15
 
     env:
-      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
+      DEVELOPER_DIR: '/Applications/${{ matrix.xcode }}.app/Contents/Developer'
       CLIENT_ID: ${{ secrets.CLIENT_ID }}
       CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
       USER_ID: ${{ secrets.USER_ID }}
@@ -99,12 +116,13 @@ jobs:
   Linux:
     name: ${{ matrix.name }}
     runs-on: ubuntu-latest
+    needs: check-xcodeproj
 
     strategy:
       matrix:
         include:
           - image: swift:6.0-jammy
-            name: "SPM (Swift 6.0, Ubuntu 22.04)"
+            name: 'SPM (Swift 6.0, Ubuntu 22.04)'
 
     container:
       image: ${{ matrix.image }}
